import fs from 'node:fs/promises';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import { Presentation, PresentationFile } from '@oai/artifact-tool';

const workspaceDir = process.cwd();
const SKILL_DIR = '/Users/brittbowman/.codex/plugins/cache/openai-primary-runtime/presentations/26.903.11726/skills/presentations';
const RUNTIME_PYTHON = '/Users/brittbowman/.cache/codex-runtimes/codex-primary-runtime/dependencies/python/bin/python3';
const FINAL_PPTX = path.join(workspaceDir, 'outputs/uni-capital-workshop/uni-eti-working-session-with-lee.pptx');
const { resolvePresentationFont, finalizePresentation } = await import(pathToFileURL(path.join(SKILL_DIR, 'container_tools/artifact_tool_utils.mjs')).href);
const font = resolvePresentationFont({ fontFamily: 'Arial' });
const P = { navy:'#071426', panel:'#0B1E35', cyan:'#00D5EA', white:'#F7F9FC', muted:'#B7C4D8', line:'#37546F' };
const deck = Presentation.create({slideSize:{width:1280,height:720}});
function rect(s,l,t,w,h,fill,rad=0){return s.shapes.add({geometry:rad?'roundRect':'rect',position:{left:l,top:t,width:w,height:h},fill, line:{fill:'none',width:0}})}
function box(s,txt,l,t,w,h,size=24,color=P.white,bold=false){const x=s.shapes.add({geometry:'textbox',position:{left:l,top:t,width:w,height:h},fill:'none',line:{fill:'none',width:0}});x.text=txt;x.text.style={typeface:font,fontSize:size,color,bold,autoFit:'shrinkText'};return x}
function base(n,title,sub=''){const s=deck.slides.add();s.background.fill=P.navy;rect(s,0,0,1280,6,P.cyan);box(s,'BRITT BOWMAN LLC  ·  WORKING SESSION WITH LEE',64,38,700,22,13,P.cyan,true);box(s,String(n).padStart(2,'0'),1160,38,55,22,13,P.muted,true);box(s,title,64,95,1080,70,37,P.white,true);if(sub)box(s,sub,64,174,1090,54,18,P.muted,false);rect(s,64,662,1152,1,P.line);box(s,'UNI + ETI  ·  SEPTEMBER 8, 2026',64,677,550,18,11,P.muted,true);return s}
function card(s,x,y,w,h,head,body,accent=true){rect(s,x,y,w,h,P.panel,10);box(s,head,x+20,y+18,w-40,28,18,accent?P.cyan:P.white,true);box(s,body,x+20,y+57,w-40,h-72,15,P.muted,false)}

{const s=deck.slides.add();s.background.fill=P.navy;rect(s,0,0,1280,6,P.cyan);box(s,'BRITT BOWMAN LLC  ·  WORKING SESSION WITH LEE',70,52,750,24,14,P.cyan,true);box(s,'UNI + ETI',70,116,700,28,18,P.muted,true);box(s,'What I think we need\nto get honest about',70,183,940,150,57,P.white,true);box(s,'I’ve gone through what you sent me. I understand the company you’re trying to build. This is a way to work out what has to happen next for that company to become real.',70,370,930,62,20,P.muted,false);box(s,'Route',70,505,205,40,31,P.cyan,true);box(s,'Proof',360,505,205,40,31,P.cyan,true);box(s,'Commitment',650,505,280,40,31,P.cyan,true);box(s,'September 8, 2026',70,630,340,22,14,P.muted,true)}
{const s=base(1,'What we’re actually deciding','I don’t think the question is whether the thesis is interesting. I think the question is what turns it into a company.');card(s,64,275,350,205,'What you’re building','An independent evidence and trust layer for consequential workforce decisions.');card(s,465,275,350,205,'What I’m worried about','Research and a product idea don’t yet create a capital plan, a company, or an acquisition target.');card(s,866,275,350,205,'What I want us to leave with','A route we agree on, what it needs to prove, and who has to commit to it.');box(s,'Question: Who besides you needs to believe this enough to put something at risk?',64,540,1090,35,23,P.white,true)}
{const s=base(2,'There are a few ways to get from idea to money','We need to choose the one you’re actually trying to do for the next year.');card(s,64,264,535,132,'Customer-funded','Paying customers show there’s a painful problem, a product people value, and a path to repeatable revenue.');card(s,647,264,535,132,'Pre-seed or angel-funded','Capital helps a real team move faster against a clear plan. It doesn’t replace evidence that other people care.');card(s,64,425,535,132,'Strategic-partner-led','A serious institution or platform has a real gap and is willing to put time, reputation, or money behind working with you.');card(s,647,425,535,132,'Acquisition','Something that might happen after UNI has built a team, customers, and an asset a buyer wants.');box(s,'Question: Which one is the plan, and what would tell us it’s working?',64,596,1090,30,22,P.white,true)}
{const s=base(3,'What someone else has to see','If you want money, somebody outside UNI has to see more than a smart idea.');card(s,64,270,260,220,'Team','Who is building this with you? What has to be in the company or formally committed?');card(s,360,270,260,220,'A real commitment','Who will put something at risk: a customer, a design partner, an investor, or an institution?');card(s,656,270,260,220,'Something that works','What’s the smallest thing UNI can put in the world that proves its point?');card(s,952,270,260,220,'An asset that grows','What does UNI build that a big incumbent can’t just copy later?');box(s,'Question: What would make us say, a year from now, that this is working?',64,555,1090,32,22,P.white,true)}
{const s=base(4,'The customer question','I don’t think early customers automatically make UNI a hiring-assessment company. It depends on what they buy and what it proves.');box(s,'The job is to find a first use case that creates real value for the customer and demonstrates the larger trust-layer idea.',64,255,1120,58,24,P.white,true);card(s,64,365,350,155,'One decision','Which workforce decision do we start with?');card(s,465,365,350,155,'One thing UNI makes real','What record, credential, or proof object does the customer actually use?');card(s,866,365,350,155,'One commitment','Who will rely on it strongly enough to create proof that matters?');box(s,'Question: What would make an investor say this is more than another assessment product?',64,572,1120,34,20,P.muted,true)}
{const s=base(5,'Where we land','This doesn’t need to be perfect today. It needs to be honest enough for us to see what needs work.');card(s,64,260,535,115,'Route we chose','________________________________________',false);card(s,647,260,535,115,'What we need to prove in 12 months','________________________________________',false);card(s,64,407,535,115,'Who has to commit','________________________________________',false);card(s,647,407,535,115,'Asset UNI needs to build','________________________________________',false);box(s,'The next rational decision: _________________________________',64,575,900,34,23,P.white,true);box(s,'We don’t need to predict a specific acquisition. We need to know what would make this company worth funding and eventually worth buying.',64,620,1080,22,14,P.muted,false)}

for (const slide of deck.slides.items) slide.speakerNotes.textFrame.setText('Internal decision workshop. Uses Lee Warren’s supplied UNI + ETI materials and the paid-session pressure-test context.');
const stagingDir=path.join(workspaceDir,'.codex-finalizer');await fs.mkdir(stagingDir,{recursive:true});await fs.mkdir(path.dirname(FINAL_PPTX),{recursive:true});
const candidatePath=path.join(stagingDir,'uni-eti-working-session-with-lee-candidate.pptx');await (await PresentationFile.exportPptx(deck)).save(candidatePath);
const result=await finalizePresentation({workspaceDir,candidatePath,finalPath:FINAL_PPTX,pythonExecutable:RUNTIME_PYTHON,integrityValidatorPath:path.join(SKILL_DIR,'container_tools/inspect_presentation_package_integrity.py'),layoutValidatorPath:path.join(SKILL_DIR,'container_tools/inspect_presentation_layout_geometry.py'),layoutArgs:['--expected-slide-size-emu','12192000,6858000','--validate-bullet-geometry','--validate-heading-fit'],explicitTotalSlideCount:6,requiredNativeTableOwnerSlides:[],fontPolicy:{basis:'design',families:[font]},verifyArtifactToolImport:true,receiptPath:path.join(stagingDir,'uni-eti-working-session-with-lee.validation.json')});
console.log(JSON.stringify({finalPath:FINAL_PPTX,result},null,2));
