-- Give the cloud sweep its own credential, generated where nobody can read it.
--
-- The previous design asked Britt to paste HUB_INTEGRATION_SECRET into Vault. That
-- was wrong twice over. It was a manual step that did not need to be manual, and it
-- reused one secret across two unrelated authority boundaries:
--
--   HUB_INTEGRATION_SECRET  marketing OS  ->  approval gateway   (creates approvals)
--   cloud_sweep_secret      pg_cron       ->  funnel-sweep       (reads and parks)
--
-- Those grant different things and must not share a value. This one is generated by
-- the database from gen_random_bytes, stored in Vault, and read back only by the
-- scheduler and by the function it calls. It is never printed, committed, passed on
-- a command line, or seen by any human or agent.

CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA extensions;

DO $$
DECLARE
  existing uuid;
BEGIN
  SELECT id INTO existing FROM vault.secrets WHERE name = 'cloud_sweep_secret' LIMIT 1;
  IF existing IS NULL THEN
    PERFORM vault.create_secret(
      encode(extensions.gen_random_bytes(32), 'hex'),
      'cloud_sweep_secret',
      'Authenticates pg_cron to the funnel-sweep Edge Function. Generated in-database; no human or agent has ever seen it. Rotate by deleting this row and re-running this migration.'
    );
    RAISE NOTICE 'cloud_sweep_secret created';
  ELSE
    RAISE NOTICE 'cloud_sweep_secret already exists; left alone';
  END IF;
END $$;

-- The scheduler reads its own secret, not the integration secret.
CREATE OR REPLACE FUNCTION public.drive_hub_sweep_secret()
RETURNS text LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE v text;
BEGIN
  SELECT decrypted_secret INTO v
  FROM vault.decrypted_secrets WHERE name = 'cloud_sweep_secret' LIMIT 1;
  RETURN v;
EXCEPTION WHEN OTHERS THEN
  RETURN NULL;
END;
$$;

-- The function being called verifies against the same Vault row, so the value never
-- has to exist as an environment variable anywhere.
CREATE OR REPLACE FUNCTION public.drive_hub_verify_sweep_secret(supplied text)
RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE v text;
BEGIN
  SELECT decrypted_secret INTO v FROM vault.decrypted_secrets WHERE name = 'cloud_sweep_secret' LIMIT 1;
  IF v IS NULL OR supplied IS NULL OR length(supplied) = 0 THEN RETURN false; END IF;
  -- Constant-time compare, so a wrong guess reveals nothing about how wrong it was.
  RETURN hmac(v, 'cmp', 'sha256') = hmac(supplied, 'cmp', 'sha256');
EXCEPTION WHEN OTHERS THEN
  RETURN false;
END;
$$;

REVOKE ALL ON FUNCTION public.drive_hub_sweep_secret() FROM public, anon, authenticated;
REVOKE ALL ON FUNCTION public.drive_hub_verify_sweep_secret(text) FROM public, anon;
GRANT EXECUTE ON FUNCTION public.drive_hub_verify_sweep_secret(text) TO service_role;
